FORMAT: 1A
HOST: http://quotes.rest

# Quotes 

This is the documentation for the world famous quotes API https://theysaidso.com/api . They Said So Quotes API offers a complete feature rich REST API access to its quotes platform. If you are a subscriber and you are trying this from a console add 'X-TheySaidSo-Api-Secret' header and add your api key as the header value.

# Group Quote of the day
This is a public portion of the API. Anyone can access but the calls are rate limited.

## Quote of the day Categories [/qod/categories] 
Return all the available categories for Quote of the day. 

### List All Quote of the Categories [GET]

+ Request
  
  + Headers
  
            Accept: application/json
            
+ Response 200 (application/json)
        
        {
            "success": {
                "total": 8
            },
            "contents": {
                "categories": {
                    "inspire": "Inspiring Quote of the day",
                    "management": "Management Quote of the day",
                    "sports": "Sports Quote of the day",
                    "life": "Quote of the day about life",
                    "funny": "Funny Quote of the day",
                    "love": "Quote of the day about Love",
                    "art": "Art quote of the day ",
                    "students": "Quote of the day for students"
                },
                "copyright": "2013-15 http://theysaidso.com"
            }
        }

## Get Quote of the day [/qod{?category}]
Get a quote of the day. The category can be any of the categories listed in previous call. Be sure to check the list often as we update and add the QOD categories very often.
### Get a Quote of the day from a specific category [GET]


+ Parameters
    + category  (string) - QOD Category to get the Quote 
    
+ Request
  
  + Headers
  
            Accept: application/json
            
+ Response 201 (application/json)

    + Headers

            Location: /qod
            

    + Body

            {
                "success": {
                    "total": 1
                },
                "contents": {
                    "quotes": [
                        {
                            "quote": "People are like stained glass windows. \r\n They sparkle and shine when the sun is out,\r\n but when the darkness sets in,\r\n their true beauty is revealed only if there is a light from within.",
                            "length": "188",
                            "author": "Elizabeth Kubler Ross",
                            "tags": [
                                "inspire",
                                "people",
                                "true-beauty"
                            ],
                            "category": "inspire",
                            "date": "2016-07-21",
                            "title": "Inspiring Quote of the day",
                            "background": "https://theysaidso.com/img/bgs/man_on_the_mountain.jpg",
                            "id": "W4YG10QyNrQurhRyoFZkRweF"
                        }
                    ]
                }
            }
            
            
            

# Group Random Quotes
This is part of private API. You need an API Key to access these. To get an API Key visit https://theysaidso.com/api

## Get a random Quote [/quote{?author}{?category}{?minlength}{?maxlength}] 
Get a random quote from theysaidso.com. 

### Get a random quote [GET]


+ Parameters
    + category  (string, optional) - Category/tag/topic of of the Quote
    + author    (string, optional) - Author of the quote
    + minlength (number, optional) - Minimum length of the quote string
    + maxlength (number, optional) - Maximum length of the quote string
    
+ Request
  
  + Headers
  
            Accept: application/json
                
+ Response 201 (application/json)

    + Headers

            Location: /quote

    + Body

            {
                "success":
                    {
                        "total":1
                    },
                "contents":
                    {
                        "quote": "We need real leadership, Democrat, Republican and independent to stand up and say, we have to live within our means.",
                        "author":"Tom Coburn",
                        "id":"hjlWreIUIrPr_FdD_Xv8QweF",
                        "requested_category":"leadership",
                        "categories":["leadership","management"]
                    }
            }